<?xml version="1.0"?>
<package format="2">
  <name>mpcplanning</name>
  <version>1.0.0</version>
  <description>
    Real-time Macro-Intercept Model Predictive Control (MPC) node for Agile Quadrotor Flight.
    Interfaced with PX4 via MAVROS for high-speed head-on engagement.
  </description>

  <maintainer email="geffen@expert.robotics">Geffen</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>roslib</depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  
  <depend>mavros_msgs</depend>

  <export>
    </export>
</package>
